package model.pojo;
// Generated 13-ene-2015 9:45:59 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaProducto generated by hbm2java
 */
@Entity
@Table(name = "categoria_producto", catalog = "peluqueria"
)
public class CategoriaProducto implements java.io.Serializable {

    private String nombreCategoria;
    private Set<Producto> productos = new HashSet<>(0);

    public CategoriaProducto() {
    }

    public CategoriaProducto(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    public CategoriaProducto(String nombreCategoria, Set<Producto> productos) {
        this.nombreCategoria = nombreCategoria;
        this.productos = productos;
    }

    @Id

    @Column(name = "nombre_categoria", unique = true, nullable = false, length = 40)
    public String getNombreCategoria() {
        return this.nombreCategoria;
    }

    public void setNombreCategoria(String nombreCategoria) {
        this.nombreCategoria = nombreCategoria;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "categoriaProducto")
    @JsonManagedReference(value = "producto-categoria")
    public Set<Producto> getProductos() {
        return this.productos;
    }

    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }

}
