package model.pojo;
// Generated 13-ene-2015 9:45:59 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LineaProducto generated by hbm2java
 */
@Entity
@Table(name = "linea_producto", catalog = "peluqueria"
)
public class LineaProducto implements java.io.Serializable {

    private Integer idlineaProducto;
    private OrdenProducto ordenProducto;
    private Producto producto;
    private Integer cantidadOrdenada;

    public LineaProducto() {
    }

    public LineaProducto(OrdenProducto ordenProducto, Producto producto) {
        this.ordenProducto = ordenProducto;
        this.producto = producto;
    }

    public LineaProducto(OrdenProducto ordenProducto, Producto producto, Integer cantidadOrdenada) {
        this.ordenProducto = ordenProducto;
        this.producto = producto;
        this.cantidadOrdenada = cantidadOrdenada;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idlineaProducto", unique = true, nullable = false)
    public Integer getIdlineaProducto() {
        return this.idlineaProducto;
    }

    public void setIdlineaProducto(Integer idlineaProducto) {
        this.idlineaProducto = idlineaProducto;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "orden_producto_idcompra", nullable = false)
    @JsonBackReference(value = "lineaproducto-ordenproducto")
    public OrdenProducto getOrdenProducto() {
        return this.ordenProducto;
    }

    public void setOrdenProducto(OrdenProducto ordenProducto) {
        this.ordenProducto = ordenProducto;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "producto_idproducto", nullable = false)
    @JsonBackReference(value = "producto-lineaproducto")
    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    @Column(name = "cantidad_ordenada")
    public Integer getCantidadOrdenada() {
        return this.cantidadOrdenada;
    }

    public void setCantidadOrdenada(Integer cantidadOrdenada) {
        this.cantidadOrdenada = cantidadOrdenada;
    }

}
