package model.pojo;
// Generated 13-ene-2015 9:45:59 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoInventario generated by hbm2java
 */
@Entity
@Table(name = "producto_inventario", catalog = "peluqueria"
)
public class ProductoInventario implements java.io.Serializable {

    private Integer idproductoInventario;
    private Producto producto;
    private Date fechaInventario;
    private Integer cantidadEnStock;

    public ProductoInventario() {
    }

    public ProductoInventario(Producto producto) {
        this.producto = producto;
    }

    public ProductoInventario(Producto producto, Date fechaInventario, Integer cantidadEnStock) {
        this.producto = producto;
        this.fechaInventario = fechaInventario;
        this.cantidadEnStock = cantidadEnStock;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idproducto_inventario", unique = true, nullable = false)
    public Integer getIdproductoInventario() {
        return this.idproductoInventario;
    }

    public void setIdproductoInventario(Integer idproductoInventario) {
        this.idproductoInventario = idproductoInventario;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "producto_idproducto", nullable = false)
    @JsonBackReference(value = "producto-inventarios")
    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inventario", length = 10)
    public Date getFechaInventario() {
        return this.fechaInventario;
    }

    public void setFechaInventario(Date fechaInventario) {
        this.fechaInventario = fechaInventario;
    }

    @Column(name = "cantidad_en_stock")
    public Integer getCantidadEnStock() {
        return this.cantidadEnStock;
    }

    public void setCantidadEnStock(Integer cantidadEnStock) {
        this.cantidadEnStock = cantidadEnStock;
    }

}
