package model.pojo;
// Generated 13-ene-2015 9:45:59 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "peluqueria"
)
public class Producto implements java.io.Serializable {

    private Integer idproducto;
    private CategoriaProducto categoriaProducto;
    private String nombreProducto;
    private String capacidadProducto;
    private String precioCompra;
    private String precioVenta;
    private String precioServicio;
    private String barCodigo;
    private Set<LineaProducto> lineaProductos = new HashSet<>(0);
    private Set<LineaProductoServicio> lineaProductoServicios = new HashSet<>(0);
    private Set<ProductoInventario> productoInventarios = new HashSet<>(0);

    public Producto() {
    }

    public Producto(CategoriaProducto categoriaProducto) {
        this.categoriaProducto = categoriaProducto;
    }

    public Producto(CategoriaProducto categoriaProducto, String nombreProducto, String capacidadProducto, String precioCompra, String precioVenta, String precioServicio, String barCodigo, Set<LineaProducto> lineaProductos, Set<LineaProductoServicio> lineaProductoServicios, Set<ProductoInventario> productoInventarios) {
        this.categoriaProducto = categoriaProducto;
        this.nombreProducto = nombreProducto;
        this.capacidadProducto = capacidadProducto;
        this.precioCompra = precioCompra;
        this.precioVenta = precioVenta;
        this.precioServicio = precioServicio;
        this.barCodigo = barCodigo;
        this.lineaProductos = lineaProductos;
        this.lineaProductoServicios = lineaProductoServicios;
        this.productoInventarios = productoInventarios;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idproducto", unique = true, nullable = false)
    public Integer getIdproducto() {
        return this.idproducto;
    }

    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "categoriaProducto", nullable = false)
    @JsonBackReference(value = "producto-categoria")
    public CategoriaProducto getCategoriaProducto() {
        return this.categoriaProducto;
    }

    public void setCategoriaProducto(CategoriaProducto categoriaProducto) {
        this.categoriaProducto = categoriaProducto;
    }

    @Column(name = "nombre_producto", length = 100)
    public String getNombreProducto() {
        return this.nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    @Column(name = "capacidad_producto", length = 8)
    public String getCapacidadProducto() {
        return this.capacidadProducto;
    }

    public void setCapacidadProducto(String capacidadProducto) {
        this.capacidadProducto = capacidadProducto;
    }

    @Column(name = "precio_compra", length = 8)
    public String getPrecioCompra() {
        return this.precioCompra;
    }

    public void setPrecioCompra(String precioCompra) {
        this.precioCompra = precioCompra;
    }

    @Column(name = "precio_venta", length = 8)
    public String getPrecioVenta() {
        return this.precioVenta;
    }

    public void setPrecioVenta(String precioVenta) {
        this.precioVenta = precioVenta;
    }

    @Column(name = "precio_servicio", length = 8)
    public String getPrecioServicio() {
        return this.precioServicio;
    }

    public void setPrecioServicio(String precioServicio) {
        this.precioServicio = precioServicio;
    }

    @Column(name = "bar_codigo", length = 20)
    public String getBarCodigo() {
        return this.barCodigo;
    }

    public void setBarCodigo(String barCodigo) {
        this.barCodigo = barCodigo;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "producto")
    @JsonManagedReference(value = "producto-lineaproducto")
    public Set<LineaProducto> getLineaProductos() {
        return this.lineaProductos;
    }

    public void setLineaProductos(Set<LineaProducto> lineaProductos) {
        this.lineaProductos = lineaProductos;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "producto")
    @JsonManagedReference(value = "producto-lineaproductoservicios")
    public Set<LineaProductoServicio> getLineaProductoServicios() {
        return this.lineaProductoServicios;
    }

    public void setLineaProductoServicios(Set<LineaProductoServicio> lineaProductoServicios) {
        this.lineaProductoServicios = lineaProductoServicios;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "producto")
    @JsonManagedReference(value = "producto-inventarios")
    public Set<ProductoInventario> getProductoInventarios() {
        return this.productoInventarios;
    }

    public void setProductoInventarios(Set<ProductoInventario> productoInventarios) {
        this.productoInventarios = productoInventarios;
    }

}
