package model.pojo;
// Generated 13-ene-2015 9:45:59 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Puestoempleado generated by hbm2java
 */
@Entity
@Table(name="puestoempleado"
    ,catalog="peluqueria"
)
public class Puestoempleado  implements java.io.Serializable {


     private Integer idpuestoEmpleado;
     private String nombrePuesto;
     private Set<Empleado> empleados = new HashSet<>(0);

    public Puestoempleado() {
    }

	
    public Puestoempleado(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public Puestoempleado(String nombrePuesto, Set<Empleado> empleados) {
       this.nombrePuesto = nombrePuesto;
       this.empleados = empleados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpuestoEmpleado", unique=true, nullable=false)
    public Integer getIdpuestoEmpleado() {
        return this.idpuestoEmpleado;
    }
    
    public void setIdpuestoEmpleado(Integer idpuestoEmpleado) {
        this.idpuestoEmpleado = idpuestoEmpleado;
    }

    
    @Column(name="nombre_puesto", nullable=false, length=30)
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="puestoempleado")
@JsonManagedReference(value = "empleado-puestoempleado")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


